[package]
name = "rust"
version = "0.1.0"
authors = ["Ben Gamari <ben@smart-cactus.org>"]

[dependencies]
num-traits = "0.2.6"
rand = "0.6.5"
nalgebra = "0.18"

[[bin]]
name = "rust"
path = "main.rs"
